apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2023mt03641
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2023mt03641
  template:
    metadata:
      labels:
        app: app2023mt03641
    spec:
      containers:
      - name: cnr-2023mt03641
        image: shats1234/img-2023mt03641:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config-2023mt03641
      - name: metrics-exporter
        image: nginx/nginx-prometheus-exporter
        args:
        - -nginx.scrape-uri=http://localhost:8000/metrics
        ports:
        - containerPort: 9113