apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metrics-rules-2023mt03641
spec:
  groups:
  - name: fastapi-metrics
    rules:
    - alert: HighCPUUsage
      expr: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace="default", pod=~"deployment-.*"} > 0.5
      for: 5m
      labels:
        severity: warning

